ignore:
  - "src/tests"

comment:
  layout: "header, diff, tree, changes, sunburst"
  require_changes: false
  
  coverage:
  status:
    patch:
      default:
        enabled: no
    project:
      default:
        enabled: no

