// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_F141EPICSNT_BRIGHTNESS_FLATBUFS_F141_EPICS_NT_H_
#define FLATBUFFERS_GENERATED_F141EPICSNT_BRIGHTNESS_FLATBUFS_F141_EPICS_NT_H_

#include "flatbuffers/flatbuffers.h"

namespace BrightnESS {
namespace FlatBufs {
namespace f141_epics_nt {

struct timeStamp_t;

struct NTScalarByte;

struct NTScalarUByte;

struct NTScalarShort;

struct NTScalarUShort;

struct NTScalarInt;

struct NTScalarUInt;

struct NTScalarLong;

struct NTScalarULong;

struct NTScalarFloat;

struct NTScalarDouble;

struct NTScalarArrayByte;

struct NTScalarArrayUByte;

struct NTScalarArrayShort;

struct NTScalarArrayUShort;

struct NTScalarArrayInt;

struct NTScalarArrayUInt;

struct NTScalarArrayLong;

struct NTScalarArrayULong;

struct NTScalarArrayFloat;

struct NTScalarArrayDouble;

struct fwdinfo_t;

struct fwdinfo_2_t;

struct EpicsPV;

enum class PV : uint8_t {
  NONE = 0,
  NTScalarByte = 1,
  NTScalarUByte = 2,
  NTScalarShort = 3,
  NTScalarUShort = 4,
  NTScalarInt = 5,
  NTScalarUInt = 6,
  NTScalarLong = 7,
  NTScalarULong = 8,
  NTScalarFloat = 9,
  NTScalarDouble = 10,
  NTScalarArrayByte = 11,
  NTScalarArrayUByte = 12,
  NTScalarArrayShort = 13,
  NTScalarArrayUShort = 14,
  NTScalarArrayInt = 15,
  NTScalarArrayUInt = 16,
  NTScalarArrayLong = 17,
  NTScalarArrayULong = 18,
  NTScalarArrayFloat = 19,
  NTScalarArrayDouble = 20,
  MIN = NONE,
  MAX = NTScalarArrayDouble
};

inline const char **EnumNamesPV() {
  static const char *names[] = {
    "NONE",
    "NTScalarByte",
    "NTScalarUByte",
    "NTScalarShort",
    "NTScalarUShort",
    "NTScalarInt",
    "NTScalarUInt",
    "NTScalarLong",
    "NTScalarULong",
    "NTScalarFloat",
    "NTScalarDouble",
    "NTScalarArrayByte",
    "NTScalarArrayUByte",
    "NTScalarArrayShort",
    "NTScalarArrayUShort",
    "NTScalarArrayInt",
    "NTScalarArrayUInt",
    "NTScalarArrayLong",
    "NTScalarArrayULong",
    "NTScalarArrayFloat",
    "NTScalarArrayDouble",
    nullptr
  };
  return names;
}

inline const char *EnumNamePV(PV e) {
  const size_t index = static_cast<int>(e);
  return EnumNamesPV()[index];
}

template<typename T> struct PVTraits {
  static const PV enum_value = PV::NONE;
};

template<> struct PVTraits<NTScalarByte> {
  static const PV enum_value = PV::NTScalarByte;
};

template<> struct PVTraits<NTScalarUByte> {
  static const PV enum_value = PV::NTScalarUByte;
};

template<> struct PVTraits<NTScalarShort> {
  static const PV enum_value = PV::NTScalarShort;
};

template<> struct PVTraits<NTScalarUShort> {
  static const PV enum_value = PV::NTScalarUShort;
};

template<> struct PVTraits<NTScalarInt> {
  static const PV enum_value = PV::NTScalarInt;
};

template<> struct PVTraits<NTScalarUInt> {
  static const PV enum_value = PV::NTScalarUInt;
};

template<> struct PVTraits<NTScalarLong> {
  static const PV enum_value = PV::NTScalarLong;
};

template<> struct PVTraits<NTScalarULong> {
  static const PV enum_value = PV::NTScalarULong;
};

template<> struct PVTraits<NTScalarFloat> {
  static const PV enum_value = PV::NTScalarFloat;
};

template<> struct PVTraits<NTScalarDouble> {
  static const PV enum_value = PV::NTScalarDouble;
};

template<> struct PVTraits<NTScalarArrayByte> {
  static const PV enum_value = PV::NTScalarArrayByte;
};

template<> struct PVTraits<NTScalarArrayUByte> {
  static const PV enum_value = PV::NTScalarArrayUByte;
};

template<> struct PVTraits<NTScalarArrayShort> {
  static const PV enum_value = PV::NTScalarArrayShort;
};

template<> struct PVTraits<NTScalarArrayUShort> {
  static const PV enum_value = PV::NTScalarArrayUShort;
};

template<> struct PVTraits<NTScalarArrayInt> {
  static const PV enum_value = PV::NTScalarArrayInt;
};

template<> struct PVTraits<NTScalarArrayUInt> {
  static const PV enum_value = PV::NTScalarArrayUInt;
};

template<> struct PVTraits<NTScalarArrayLong> {
  static const PV enum_value = PV::NTScalarArrayLong;
};

template<> struct PVTraits<NTScalarArrayULong> {
  static const PV enum_value = PV::NTScalarArrayULong;
};

template<> struct PVTraits<NTScalarArrayFloat> {
  static const PV enum_value = PV::NTScalarArrayFloat;
};

template<> struct PVTraits<NTScalarArrayDouble> {
  static const PV enum_value = PV::NTScalarArrayDouble;
};

bool VerifyPV(flatbuffers::Verifier &verifier, const void *obj, PV type);
bool VerifyPVVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types);

enum class fwdinfo_u : uint8_t {
  NONE = 0,
  fwdinfo_2_t = 1,
  MIN = NONE,
  MAX = fwdinfo_2_t
};

inline const char **EnumNamesfwdinfo_u() {
  static const char *names[] = {
    "NONE",
    "fwdinfo_2_t",
    nullptr
  };
  return names;
}

inline const char *EnumNamefwdinfo_u(fwdinfo_u e) {
  const size_t index = static_cast<int>(e);
  return EnumNamesfwdinfo_u()[index];
}

template<typename T> struct fwdinfo_uTraits {
  static const fwdinfo_u enum_value = fwdinfo_u::NONE;
};

template<> struct fwdinfo_uTraits<fwdinfo_2_t> {
  static const fwdinfo_u enum_value = fwdinfo_u::fwdinfo_2_t;
};

bool Verifyfwdinfo_u(flatbuffers::Verifier &verifier, const void *obj, fwdinfo_u type);
bool Verifyfwdinfo_uVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types);

MANUALLY_ALIGNED_STRUCT(8) timeStamp_t FLATBUFFERS_FINAL_CLASS {
 private:
  uint64_t secondsPastEpoch_;
  int32_t nanoseconds_;
  int32_t padding0__;

 public:
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "BrightnESS.FlatBufs.f141_epics_nt.timeStamp_t";
  }
  timeStamp_t() {
    memset(this, 0, sizeof(timeStamp_t));
  }
  timeStamp_t(const timeStamp_t &_o) {
    memcpy(this, &_o, sizeof(timeStamp_t));
  }
  timeStamp_t(uint64_t _secondsPastEpoch, int32_t _nanoseconds)
      : secondsPastEpoch_(flatbuffers::EndianScalar(_secondsPastEpoch)),
        nanoseconds_(flatbuffers::EndianScalar(_nanoseconds)),
        padding0__(0) {
    (void)padding0__;
  }
  uint64_t secondsPastEpoch() const {
    return flatbuffers::EndianScalar(secondsPastEpoch_);
  }
  void mutate_secondsPastEpoch(uint64_t _secondsPastEpoch) {
    flatbuffers::WriteScalar(&secondsPastEpoch_, _secondsPastEpoch);
  }
  int32_t nanoseconds() const {
    return flatbuffers::EndianScalar(nanoseconds_);
  }
  void mutate_nanoseconds(int32_t _nanoseconds) {
    flatbuffers::WriteScalar(&nanoseconds_, _nanoseconds);
  }
};
STRUCT_END(timeStamp_t, 16);

MANUALLY_ALIGNED_STRUCT(8) fwdinfo_t FLATBUFFERS_FINAL_CLASS {
 private:
  uint64_t seq_;
  uint64_t ts_data_;
  uint64_t ts_fwd_;
  uint8_t fwdix_;
  int8_t padding0__;  int16_t padding1__;  int32_t padding2__;
  uint64_t teamid_;

 public:
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "BrightnESS.FlatBufs.f141_epics_nt.fwdinfo_t";
  }
  fwdinfo_t() {
    memset(this, 0, sizeof(fwdinfo_t));
  }
  fwdinfo_t(const fwdinfo_t &_o) {
    memcpy(this, &_o, sizeof(fwdinfo_t));
  }
  fwdinfo_t(uint64_t _seq, uint64_t _ts_data, uint64_t _ts_fwd, uint8_t _fwdix, uint64_t _teamid)
      : seq_(flatbuffers::EndianScalar(_seq)),
        ts_data_(flatbuffers::EndianScalar(_ts_data)),
        ts_fwd_(flatbuffers::EndianScalar(_ts_fwd)),
        fwdix_(flatbuffers::EndianScalar(_fwdix)),
        padding0__(0),
        padding1__(0),
        padding2__(0),
        teamid_(flatbuffers::EndianScalar(_teamid)) {
    (void)padding0__;    (void)padding1__;    (void)padding2__;
  }
  uint64_t seq() const {
    return flatbuffers::EndianScalar(seq_);
  }
  void mutate_seq(uint64_t _seq) {
    flatbuffers::WriteScalar(&seq_, _seq);
  }
  uint64_t ts_data() const {
    return flatbuffers::EndianScalar(ts_data_);
  }
  void mutate_ts_data(uint64_t _ts_data) {
    flatbuffers::WriteScalar(&ts_data_, _ts_data);
  }
  uint64_t ts_fwd() const {
    return flatbuffers::EndianScalar(ts_fwd_);
  }
  void mutate_ts_fwd(uint64_t _ts_fwd) {
    flatbuffers::WriteScalar(&ts_fwd_, _ts_fwd);
  }
  uint8_t fwdix() const {
    return flatbuffers::EndianScalar(fwdix_);
  }
  void mutate_fwdix(uint8_t _fwdix) {
    flatbuffers::WriteScalar(&fwdix_, _fwdix);
  }
  uint64_t teamid() const {
    return flatbuffers::EndianScalar(teamid_);
  }
  void mutate_teamid(uint64_t _teamid) {
    flatbuffers::WriteScalar(&teamid_, _teamid);
  }
};
STRUCT_END(fwdinfo_t, 40);

struct NTScalarByte FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "BrightnESS.FlatBufs.f141_epics_nt.NTScalarByte";
  }
  enum {
    VT_VALUE = 4
  };
  int8_t value() const {
    return GetField<int8_t>(VT_VALUE, 0);
  }
  bool mutate_value(int8_t _value) {
    return SetField(VT_VALUE, _value);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_VALUE) &&
           verifier.EndTable();
  }
};

struct NTScalarByteBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(int8_t value) {
    fbb_.AddElement<int8_t>(NTScalarByte::VT_VALUE, value, 0);
  }
  NTScalarByteBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  NTScalarByteBuilder &operator=(const NTScalarByteBuilder &);
  flatbuffers::Offset<NTScalarByte> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<NTScalarByte>(end);
    return o;
  }
};

inline flatbuffers::Offset<NTScalarByte> CreateNTScalarByte(
    flatbuffers::FlatBufferBuilder &_fbb,
    int8_t value = 0) {
  NTScalarByteBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct NTScalarUByte FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "BrightnESS.FlatBufs.f141_epics_nt.NTScalarUByte";
  }
  enum {
    VT_VALUE = 4
  };
  uint8_t value() const {
    return GetField<uint8_t>(VT_VALUE, 0);
  }
  bool mutate_value(uint8_t _value) {
    return SetField(VT_VALUE, _value);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_VALUE) &&
           verifier.EndTable();
  }
};

struct NTScalarUByteBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(uint8_t value) {
    fbb_.AddElement<uint8_t>(NTScalarUByte::VT_VALUE, value, 0);
  }
  NTScalarUByteBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  NTScalarUByteBuilder &operator=(const NTScalarUByteBuilder &);
  flatbuffers::Offset<NTScalarUByte> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<NTScalarUByte>(end);
    return o;
  }
};

inline flatbuffers::Offset<NTScalarUByte> CreateNTScalarUByte(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t value = 0) {
  NTScalarUByteBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct NTScalarShort FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "BrightnESS.FlatBufs.f141_epics_nt.NTScalarShort";
  }
  enum {
    VT_VALUE = 4
  };
  int16_t value() const {
    return GetField<int16_t>(VT_VALUE, 0);
  }
  bool mutate_value(int16_t _value) {
    return SetField(VT_VALUE, _value);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int16_t>(verifier, VT_VALUE) &&
           verifier.EndTable();
  }
};

struct NTScalarShortBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(int16_t value) {
    fbb_.AddElement<int16_t>(NTScalarShort::VT_VALUE, value, 0);
  }
  NTScalarShortBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  NTScalarShortBuilder &operator=(const NTScalarShortBuilder &);
  flatbuffers::Offset<NTScalarShort> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<NTScalarShort>(end);
    return o;
  }
};

inline flatbuffers::Offset<NTScalarShort> CreateNTScalarShort(
    flatbuffers::FlatBufferBuilder &_fbb,
    int16_t value = 0) {
  NTScalarShortBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct NTScalarUShort FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "BrightnESS.FlatBufs.f141_epics_nt.NTScalarUShort";
  }
  enum {
    VT_VALUE = 4
  };
  uint16_t value() const {
    return GetField<uint16_t>(VT_VALUE, 0);
  }
  bool mutate_value(uint16_t _value) {
    return SetField(VT_VALUE, _value);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_VALUE) &&
           verifier.EndTable();
  }
};

struct NTScalarUShortBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(uint16_t value) {
    fbb_.AddElement<uint16_t>(NTScalarUShort::VT_VALUE, value, 0);
  }
  NTScalarUShortBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  NTScalarUShortBuilder &operator=(const NTScalarUShortBuilder &);
  flatbuffers::Offset<NTScalarUShort> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<NTScalarUShort>(end);
    return o;
  }
};

inline flatbuffers::Offset<NTScalarUShort> CreateNTScalarUShort(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t value = 0) {
  NTScalarUShortBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct NTScalarInt FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "BrightnESS.FlatBufs.f141_epics_nt.NTScalarInt";
  }
  enum {
    VT_VALUE = 4
  };
  int32_t value() const {
    return GetField<int32_t>(VT_VALUE, 0);
  }
  bool mutate_value(int32_t _value) {
    return SetField(VT_VALUE, _value);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_VALUE) &&
           verifier.EndTable();
  }
};

struct NTScalarIntBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(int32_t value) {
    fbb_.AddElement<int32_t>(NTScalarInt::VT_VALUE, value, 0);
  }
  NTScalarIntBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  NTScalarIntBuilder &operator=(const NTScalarIntBuilder &);
  flatbuffers::Offset<NTScalarInt> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<NTScalarInt>(end);
    return o;
  }
};

inline flatbuffers::Offset<NTScalarInt> CreateNTScalarInt(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t value = 0) {
  NTScalarIntBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct NTScalarUInt FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "BrightnESS.FlatBufs.f141_epics_nt.NTScalarUInt";
  }
  enum {
    VT_VALUE = 4
  };
  uint32_t value() const {
    return GetField<uint32_t>(VT_VALUE, 0);
  }
  bool mutate_value(uint32_t _value) {
    return SetField(VT_VALUE, _value);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_VALUE) &&
           verifier.EndTable();
  }
};

struct NTScalarUIntBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(uint32_t value) {
    fbb_.AddElement<uint32_t>(NTScalarUInt::VT_VALUE, value, 0);
  }
  NTScalarUIntBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  NTScalarUIntBuilder &operator=(const NTScalarUIntBuilder &);
  flatbuffers::Offset<NTScalarUInt> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<NTScalarUInt>(end);
    return o;
  }
};

inline flatbuffers::Offset<NTScalarUInt> CreateNTScalarUInt(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t value = 0) {
  NTScalarUIntBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct NTScalarLong FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "BrightnESS.FlatBufs.f141_epics_nt.NTScalarLong";
  }
  enum {
    VT_VALUE = 4
  };
  int64_t value() const {
    return GetField<int64_t>(VT_VALUE, 0);
  }
  bool mutate_value(int64_t _value) {
    return SetField(VT_VALUE, _value);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_VALUE) &&
           verifier.EndTable();
  }
};

struct NTScalarLongBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(int64_t value) {
    fbb_.AddElement<int64_t>(NTScalarLong::VT_VALUE, value, 0);
  }
  NTScalarLongBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  NTScalarLongBuilder &operator=(const NTScalarLongBuilder &);
  flatbuffers::Offset<NTScalarLong> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<NTScalarLong>(end);
    return o;
  }
};

inline flatbuffers::Offset<NTScalarLong> CreateNTScalarLong(
    flatbuffers::FlatBufferBuilder &_fbb,
    int64_t value = 0) {
  NTScalarLongBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct NTScalarULong FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "BrightnESS.FlatBufs.f141_epics_nt.NTScalarULong";
  }
  enum {
    VT_VALUE = 4
  };
  uint64_t value() const {
    return GetField<uint64_t>(VT_VALUE, 0);
  }
  bool mutate_value(uint64_t _value) {
    return SetField(VT_VALUE, _value);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_VALUE) &&
           verifier.EndTable();
  }
};

struct NTScalarULongBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(uint64_t value) {
    fbb_.AddElement<uint64_t>(NTScalarULong::VT_VALUE, value, 0);
  }
  NTScalarULongBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  NTScalarULongBuilder &operator=(const NTScalarULongBuilder &);
  flatbuffers::Offset<NTScalarULong> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<NTScalarULong>(end);
    return o;
  }
};

inline flatbuffers::Offset<NTScalarULong> CreateNTScalarULong(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t value = 0) {
  NTScalarULongBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct NTScalarFloat FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "BrightnESS.FlatBufs.f141_epics_nt.NTScalarFloat";
  }
  enum {
    VT_VALUE = 4
  };
  float value() const {
    return GetField<float>(VT_VALUE, 0.0f);
  }
  bool mutate_value(float _value) {
    return SetField(VT_VALUE, _value);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_VALUE) &&
           verifier.EndTable();
  }
};

struct NTScalarFloatBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(float value) {
    fbb_.AddElement<float>(NTScalarFloat::VT_VALUE, value, 0.0f);
  }
  NTScalarFloatBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  NTScalarFloatBuilder &operator=(const NTScalarFloatBuilder &);
  flatbuffers::Offset<NTScalarFloat> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<NTScalarFloat>(end);
    return o;
  }
};

inline flatbuffers::Offset<NTScalarFloat> CreateNTScalarFloat(
    flatbuffers::FlatBufferBuilder &_fbb,
    float value = 0.0f) {
  NTScalarFloatBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct NTScalarDouble FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "BrightnESS.FlatBufs.f141_epics_nt.NTScalarDouble";
  }
  enum {
    VT_VALUE = 4
  };
  double value() const {
    return GetField<double>(VT_VALUE, 0.0);
  }
  bool mutate_value(double _value) {
    return SetField(VT_VALUE, _value);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_VALUE) &&
           verifier.EndTable();
  }
};

struct NTScalarDoubleBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(double value) {
    fbb_.AddElement<double>(NTScalarDouble::VT_VALUE, value, 0.0);
  }
  NTScalarDoubleBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  NTScalarDoubleBuilder &operator=(const NTScalarDoubleBuilder &);
  flatbuffers::Offset<NTScalarDouble> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<NTScalarDouble>(end);
    return o;
  }
};

inline flatbuffers::Offset<NTScalarDouble> CreateNTScalarDouble(
    flatbuffers::FlatBufferBuilder &_fbb,
    double value = 0.0) {
  NTScalarDoubleBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct NTScalarArrayByte FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "BrightnESS.FlatBufs.f141_epics_nt.NTScalarArrayByte";
  }
  enum {
    VT_VALUE = 4
  };
  const flatbuffers::Vector<int8_t> *value() const {
    return GetPointer<const flatbuffers::Vector<int8_t> *>(VT_VALUE);
  }
  flatbuffers::Vector<int8_t> *mutable_value() {
    return GetPointer<flatbuffers::Vector<int8_t> *>(VT_VALUE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_VALUE) &&
           verifier.Verify(value()) &&
           verifier.EndTable();
  }
};

struct NTScalarArrayByteBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(flatbuffers::Offset<flatbuffers::Vector<int8_t>> value) {
    fbb_.AddOffset(NTScalarArrayByte::VT_VALUE, value);
  }
  NTScalarArrayByteBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  NTScalarArrayByteBuilder &operator=(const NTScalarArrayByteBuilder &);
  flatbuffers::Offset<NTScalarArrayByte> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<NTScalarArrayByte>(end);
    return o;
  }
};

inline flatbuffers::Offset<NTScalarArrayByte> CreateNTScalarArrayByte(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<int8_t>> value = 0) {
  NTScalarArrayByteBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline flatbuffers::Offset<NTScalarArrayByte> CreateNTScalarArrayByteDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<int8_t> *value = nullptr) {
  return BrightnESS::FlatBufs::f141_epics_nt::CreateNTScalarArrayByte(
      _fbb,
      value ? _fbb.CreateVector<int8_t>(*value) : 0);
}

struct NTScalarArrayUByte FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "BrightnESS.FlatBufs.f141_epics_nt.NTScalarArrayUByte";
  }
  enum {
    VT_VALUE = 4
  };
  const flatbuffers::Vector<uint8_t> *value() const {
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_VALUE);
  }
  flatbuffers::Vector<uint8_t> *mutable_value() {
    return GetPointer<flatbuffers::Vector<uint8_t> *>(VT_VALUE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_VALUE) &&
           verifier.Verify(value()) &&
           verifier.EndTable();
  }
};

struct NTScalarArrayUByteBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> value) {
    fbb_.AddOffset(NTScalarArrayUByte::VT_VALUE, value);
  }
  NTScalarArrayUByteBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  NTScalarArrayUByteBuilder &operator=(const NTScalarArrayUByteBuilder &);
  flatbuffers::Offset<NTScalarArrayUByte> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<NTScalarArrayUByte>(end);
    return o;
  }
};

inline flatbuffers::Offset<NTScalarArrayUByte> CreateNTScalarArrayUByte(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> value = 0) {
  NTScalarArrayUByteBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline flatbuffers::Offset<NTScalarArrayUByte> CreateNTScalarArrayUByteDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *value = nullptr) {
  return BrightnESS::FlatBufs::f141_epics_nt::CreateNTScalarArrayUByte(
      _fbb,
      value ? _fbb.CreateVector<uint8_t>(*value) : 0);
}

struct NTScalarArrayShort FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "BrightnESS.FlatBufs.f141_epics_nt.NTScalarArrayShort";
  }
  enum {
    VT_VALUE = 4
  };
  const flatbuffers::Vector<int16_t> *value() const {
    return GetPointer<const flatbuffers::Vector<int16_t> *>(VT_VALUE);
  }
  flatbuffers::Vector<int16_t> *mutable_value() {
    return GetPointer<flatbuffers::Vector<int16_t> *>(VT_VALUE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_VALUE) &&
           verifier.Verify(value()) &&
           verifier.EndTable();
  }
};

struct NTScalarArrayShortBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(flatbuffers::Offset<flatbuffers::Vector<int16_t>> value) {
    fbb_.AddOffset(NTScalarArrayShort::VT_VALUE, value);
  }
  NTScalarArrayShortBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  NTScalarArrayShortBuilder &operator=(const NTScalarArrayShortBuilder &);
  flatbuffers::Offset<NTScalarArrayShort> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<NTScalarArrayShort>(end);
    return o;
  }
};

inline flatbuffers::Offset<NTScalarArrayShort> CreateNTScalarArrayShort(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<int16_t>> value = 0) {
  NTScalarArrayShortBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline flatbuffers::Offset<NTScalarArrayShort> CreateNTScalarArrayShortDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<int16_t> *value = nullptr) {
  return BrightnESS::FlatBufs::f141_epics_nt::CreateNTScalarArrayShort(
      _fbb,
      value ? _fbb.CreateVector<int16_t>(*value) : 0);
}

struct NTScalarArrayUShort FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "BrightnESS.FlatBufs.f141_epics_nt.NTScalarArrayUShort";
  }
  enum {
    VT_VALUE = 4
  };
  const flatbuffers::Vector<uint16_t> *value() const {
    return GetPointer<const flatbuffers::Vector<uint16_t> *>(VT_VALUE);
  }
  flatbuffers::Vector<uint16_t> *mutable_value() {
    return GetPointer<flatbuffers::Vector<uint16_t> *>(VT_VALUE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_VALUE) &&
           verifier.Verify(value()) &&
           verifier.EndTable();
  }
};

struct NTScalarArrayUShortBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(flatbuffers::Offset<flatbuffers::Vector<uint16_t>> value) {
    fbb_.AddOffset(NTScalarArrayUShort::VT_VALUE, value);
  }
  NTScalarArrayUShortBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  NTScalarArrayUShortBuilder &operator=(const NTScalarArrayUShortBuilder &);
  flatbuffers::Offset<NTScalarArrayUShort> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<NTScalarArrayUShort>(end);
    return o;
  }
};

inline flatbuffers::Offset<NTScalarArrayUShort> CreateNTScalarArrayUShort(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<uint16_t>> value = 0) {
  NTScalarArrayUShortBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline flatbuffers::Offset<NTScalarArrayUShort> CreateNTScalarArrayUShortDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint16_t> *value = nullptr) {
  return BrightnESS::FlatBufs::f141_epics_nt::CreateNTScalarArrayUShort(
      _fbb,
      value ? _fbb.CreateVector<uint16_t>(*value) : 0);
}

struct NTScalarArrayInt FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "BrightnESS.FlatBufs.f141_epics_nt.NTScalarArrayInt";
  }
  enum {
    VT_VALUE = 4
  };
  const flatbuffers::Vector<int32_t> *value() const {
    return GetPointer<const flatbuffers::Vector<int32_t> *>(VT_VALUE);
  }
  flatbuffers::Vector<int32_t> *mutable_value() {
    return GetPointer<flatbuffers::Vector<int32_t> *>(VT_VALUE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_VALUE) &&
           verifier.Verify(value()) &&
           verifier.EndTable();
  }
};

struct NTScalarArrayIntBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(flatbuffers::Offset<flatbuffers::Vector<int32_t>> value) {
    fbb_.AddOffset(NTScalarArrayInt::VT_VALUE, value);
  }
  NTScalarArrayIntBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  NTScalarArrayIntBuilder &operator=(const NTScalarArrayIntBuilder &);
  flatbuffers::Offset<NTScalarArrayInt> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<NTScalarArrayInt>(end);
    return o;
  }
};

inline flatbuffers::Offset<NTScalarArrayInt> CreateNTScalarArrayInt(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<int32_t>> value = 0) {
  NTScalarArrayIntBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline flatbuffers::Offset<NTScalarArrayInt> CreateNTScalarArrayIntDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<int32_t> *value = nullptr) {
  return BrightnESS::FlatBufs::f141_epics_nt::CreateNTScalarArrayInt(
      _fbb,
      value ? _fbb.CreateVector<int32_t>(*value) : 0);
}

struct NTScalarArrayUInt FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "BrightnESS.FlatBufs.f141_epics_nt.NTScalarArrayUInt";
  }
  enum {
    VT_VALUE = 4
  };
  const flatbuffers::Vector<uint32_t> *value() const {
    return GetPointer<const flatbuffers::Vector<uint32_t> *>(VT_VALUE);
  }
  flatbuffers::Vector<uint32_t> *mutable_value() {
    return GetPointer<flatbuffers::Vector<uint32_t> *>(VT_VALUE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_VALUE) &&
           verifier.Verify(value()) &&
           verifier.EndTable();
  }
};

struct NTScalarArrayUIntBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(flatbuffers::Offset<flatbuffers::Vector<uint32_t>> value) {
    fbb_.AddOffset(NTScalarArrayUInt::VT_VALUE, value);
  }
  NTScalarArrayUIntBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  NTScalarArrayUIntBuilder &operator=(const NTScalarArrayUIntBuilder &);
  flatbuffers::Offset<NTScalarArrayUInt> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<NTScalarArrayUInt>(end);
    return o;
  }
};

inline flatbuffers::Offset<NTScalarArrayUInt> CreateNTScalarArrayUInt(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<uint32_t>> value = 0) {
  NTScalarArrayUIntBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline flatbuffers::Offset<NTScalarArrayUInt> CreateNTScalarArrayUIntDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint32_t> *value = nullptr) {
  return BrightnESS::FlatBufs::f141_epics_nt::CreateNTScalarArrayUInt(
      _fbb,
      value ? _fbb.CreateVector<uint32_t>(*value) : 0);
}

struct NTScalarArrayLong FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "BrightnESS.FlatBufs.f141_epics_nt.NTScalarArrayLong";
  }
  enum {
    VT_VALUE = 4
  };
  const flatbuffers::Vector<int64_t> *value() const {
    return GetPointer<const flatbuffers::Vector<int64_t> *>(VT_VALUE);
  }
  flatbuffers::Vector<int64_t> *mutable_value() {
    return GetPointer<flatbuffers::Vector<int64_t> *>(VT_VALUE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_VALUE) &&
           verifier.Verify(value()) &&
           verifier.EndTable();
  }
};

struct NTScalarArrayLongBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(flatbuffers::Offset<flatbuffers::Vector<int64_t>> value) {
    fbb_.AddOffset(NTScalarArrayLong::VT_VALUE, value);
  }
  NTScalarArrayLongBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  NTScalarArrayLongBuilder &operator=(const NTScalarArrayLongBuilder &);
  flatbuffers::Offset<NTScalarArrayLong> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<NTScalarArrayLong>(end);
    return o;
  }
};

inline flatbuffers::Offset<NTScalarArrayLong> CreateNTScalarArrayLong(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<int64_t>> value = 0) {
  NTScalarArrayLongBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline flatbuffers::Offset<NTScalarArrayLong> CreateNTScalarArrayLongDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<int64_t> *value = nullptr) {
  return BrightnESS::FlatBufs::f141_epics_nt::CreateNTScalarArrayLong(
      _fbb,
      value ? _fbb.CreateVector<int64_t>(*value) : 0);
}

struct NTScalarArrayULong FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "BrightnESS.FlatBufs.f141_epics_nt.NTScalarArrayULong";
  }
  enum {
    VT_VALUE = 4
  };
  const flatbuffers::Vector<uint64_t> *value() const {
    return GetPointer<const flatbuffers::Vector<uint64_t> *>(VT_VALUE);
  }
  flatbuffers::Vector<uint64_t> *mutable_value() {
    return GetPointer<flatbuffers::Vector<uint64_t> *>(VT_VALUE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_VALUE) &&
           verifier.Verify(value()) &&
           verifier.EndTable();
  }
};

struct NTScalarArrayULongBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(flatbuffers::Offset<flatbuffers::Vector<uint64_t>> value) {
    fbb_.AddOffset(NTScalarArrayULong::VT_VALUE, value);
  }
  NTScalarArrayULongBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  NTScalarArrayULongBuilder &operator=(const NTScalarArrayULongBuilder &);
  flatbuffers::Offset<NTScalarArrayULong> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<NTScalarArrayULong>(end);
    return o;
  }
};

inline flatbuffers::Offset<NTScalarArrayULong> CreateNTScalarArrayULong(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<uint64_t>> value = 0) {
  NTScalarArrayULongBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline flatbuffers::Offset<NTScalarArrayULong> CreateNTScalarArrayULongDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint64_t> *value = nullptr) {
  return BrightnESS::FlatBufs::f141_epics_nt::CreateNTScalarArrayULong(
      _fbb,
      value ? _fbb.CreateVector<uint64_t>(*value) : 0);
}

struct NTScalarArrayFloat FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "BrightnESS.FlatBufs.f141_epics_nt.NTScalarArrayFloat";
  }
  enum {
    VT_VALUE = 4
  };
  const flatbuffers::Vector<float> *value() const {
    return GetPointer<const flatbuffers::Vector<float> *>(VT_VALUE);
  }
  flatbuffers::Vector<float> *mutable_value() {
    return GetPointer<flatbuffers::Vector<float> *>(VT_VALUE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_VALUE) &&
           verifier.Verify(value()) &&
           verifier.EndTable();
  }
};

struct NTScalarArrayFloatBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(flatbuffers::Offset<flatbuffers::Vector<float>> value) {
    fbb_.AddOffset(NTScalarArrayFloat::VT_VALUE, value);
  }
  NTScalarArrayFloatBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  NTScalarArrayFloatBuilder &operator=(const NTScalarArrayFloatBuilder &);
  flatbuffers::Offset<NTScalarArrayFloat> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<NTScalarArrayFloat>(end);
    return o;
  }
};

inline flatbuffers::Offset<NTScalarArrayFloat> CreateNTScalarArrayFloat(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<float>> value = 0) {
  NTScalarArrayFloatBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline flatbuffers::Offset<NTScalarArrayFloat> CreateNTScalarArrayFloatDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<float> *value = nullptr) {
  return BrightnESS::FlatBufs::f141_epics_nt::CreateNTScalarArrayFloat(
      _fbb,
      value ? _fbb.CreateVector<float>(*value) : 0);
}

struct NTScalarArrayDouble FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "BrightnESS.FlatBufs.f141_epics_nt.NTScalarArrayDouble";
  }
  enum {
    VT_VALUE = 4
  };
  const flatbuffers::Vector<double> *value() const {
    return GetPointer<const flatbuffers::Vector<double> *>(VT_VALUE);
  }
  flatbuffers::Vector<double> *mutable_value() {
    return GetPointer<flatbuffers::Vector<double> *>(VT_VALUE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_VALUE) &&
           verifier.Verify(value()) &&
           verifier.EndTable();
  }
};

struct NTScalarArrayDoubleBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(flatbuffers::Offset<flatbuffers::Vector<double>> value) {
    fbb_.AddOffset(NTScalarArrayDouble::VT_VALUE, value);
  }
  NTScalarArrayDoubleBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  NTScalarArrayDoubleBuilder &operator=(const NTScalarArrayDoubleBuilder &);
  flatbuffers::Offset<NTScalarArrayDouble> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<NTScalarArrayDouble>(end);
    return o;
  }
};

inline flatbuffers::Offset<NTScalarArrayDouble> CreateNTScalarArrayDouble(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<double>> value = 0) {
  NTScalarArrayDoubleBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline flatbuffers::Offset<NTScalarArrayDouble> CreateNTScalarArrayDoubleDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<double> *value = nullptr) {
  return BrightnESS::FlatBufs::f141_epics_nt::CreateNTScalarArrayDouble(
      _fbb,
      value ? _fbb.CreateVector<double>(*value) : 0);
}

struct fwdinfo_2_t FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "BrightnESS.FlatBufs.f141_epics_nt.fwdinfo_2_t";
  }
  enum {
    VT_SEQ_DATA = 4,
    VT_SEQ_FWD = 6,
    VT_TS_DATA = 8,
    VT_TS_FWD = 10,
    VT_FWDIX = 12,
    VT_TEAMID = 14
  };
  uint64_t seq_data() const {
    return GetField<uint64_t>(VT_SEQ_DATA, 0);
  }
  bool mutate_seq_data(uint64_t _seq_data) {
    return SetField(VT_SEQ_DATA, _seq_data);
  }
  uint64_t seq_fwd() const {
    return GetField<uint64_t>(VT_SEQ_FWD, 0);
  }
  bool mutate_seq_fwd(uint64_t _seq_fwd) {
    return SetField(VT_SEQ_FWD, _seq_fwd);
  }
  uint64_t ts_data() const {
    return GetField<uint64_t>(VT_TS_DATA, 0);
  }
  bool mutate_ts_data(uint64_t _ts_data) {
    return SetField(VT_TS_DATA, _ts_data);
  }
  uint64_t ts_fwd() const {
    return GetField<uint64_t>(VT_TS_FWD, 0);
  }
  bool mutate_ts_fwd(uint64_t _ts_fwd) {
    return SetField(VT_TS_FWD, _ts_fwd);
  }
  uint32_t fwdix() const {
    return GetField<uint32_t>(VT_FWDIX, 0);
  }
  bool mutate_fwdix(uint32_t _fwdix) {
    return SetField(VT_FWDIX, _fwdix);
  }
  uint64_t teamid() const {
    return GetField<uint64_t>(VT_TEAMID, 0);
  }
  bool mutate_teamid(uint64_t _teamid) {
    return SetField(VT_TEAMID, _teamid);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_SEQ_DATA) &&
           VerifyField<uint64_t>(verifier, VT_SEQ_FWD) &&
           VerifyField<uint64_t>(verifier, VT_TS_DATA) &&
           VerifyField<uint64_t>(verifier, VT_TS_FWD) &&
           VerifyField<uint32_t>(verifier, VT_FWDIX) &&
           VerifyField<uint64_t>(verifier, VT_TEAMID) &&
           verifier.EndTable();
  }
};

struct fwdinfo_2_tBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_seq_data(uint64_t seq_data) {
    fbb_.AddElement<uint64_t>(fwdinfo_2_t::VT_SEQ_DATA, seq_data, 0);
  }
  void add_seq_fwd(uint64_t seq_fwd) {
    fbb_.AddElement<uint64_t>(fwdinfo_2_t::VT_SEQ_FWD, seq_fwd, 0);
  }
  void add_ts_data(uint64_t ts_data) {
    fbb_.AddElement<uint64_t>(fwdinfo_2_t::VT_TS_DATA, ts_data, 0);
  }
  void add_ts_fwd(uint64_t ts_fwd) {
    fbb_.AddElement<uint64_t>(fwdinfo_2_t::VT_TS_FWD, ts_fwd, 0);
  }
  void add_fwdix(uint32_t fwdix) {
    fbb_.AddElement<uint32_t>(fwdinfo_2_t::VT_FWDIX, fwdix, 0);
  }
  void add_teamid(uint64_t teamid) {
    fbb_.AddElement<uint64_t>(fwdinfo_2_t::VT_TEAMID, teamid, 0);
  }
  fwdinfo_2_tBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  fwdinfo_2_tBuilder &operator=(const fwdinfo_2_tBuilder &);
  flatbuffers::Offset<fwdinfo_2_t> Finish() {
    const auto end = fbb_.EndTable(start_, 6);
    auto o = flatbuffers::Offset<fwdinfo_2_t>(end);
    return o;
  }
};

inline flatbuffers::Offset<fwdinfo_2_t> Createfwdinfo_2_t(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t seq_data = 0,
    uint64_t seq_fwd = 0,
    uint64_t ts_data = 0,
    uint64_t ts_fwd = 0,
    uint32_t fwdix = 0,
    uint64_t teamid = 0) {
  fwdinfo_2_tBuilder builder_(_fbb);
  builder_.add_teamid(teamid);
  builder_.add_ts_fwd(ts_fwd);
  builder_.add_ts_data(ts_data);
  builder_.add_seq_fwd(seq_fwd);
  builder_.add_seq_data(seq_data);
  builder_.add_fwdix(fwdix);
  return builder_.Finish();
}

struct EpicsPV FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "BrightnESS.FlatBufs.f141_epics_nt.EpicsPV";
  }
  enum {
    VT_NAME = 4,
    VT_PV_TYPE = 6,
    VT_PV = 8,
    VT_TIMESTAMP = 10,
    VT_FWDINFO = 12,
    VT_FWDINFO2_TYPE = 14,
    VT_FWDINFO2 = 16
  };
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  flatbuffers::String *mutable_name() {
    return GetPointer<flatbuffers::String *>(VT_NAME);
  }
  PV pv_type() const {
    return static_cast<PV>(GetField<uint8_t>(VT_PV_TYPE, 0));
  }
  bool mutate_pv_type(PV _pv_type) {
    return SetField(VT_PV_TYPE, static_cast<uint8_t>(_pv_type));
  }
  const void *pv() const {
    return GetPointer<const void *>(VT_PV);
  }
  void *mutable_pv() {
    return GetPointer<void *>(VT_PV);
  }
  const timeStamp_t *timeStamp() const {
    return GetStruct<const timeStamp_t *>(VT_TIMESTAMP);
  }
  timeStamp_t *mutable_timeStamp() {
    return GetStruct<timeStamp_t *>(VT_TIMESTAMP);
  }
  const fwdinfo_t *fwdinfo() const {
    return GetStruct<const fwdinfo_t *>(VT_FWDINFO);
  }
  fwdinfo_t *mutable_fwdinfo() {
    return GetStruct<fwdinfo_t *>(VT_FWDINFO);
  }
  fwdinfo_u fwdinfo2_type() const {
    return static_cast<fwdinfo_u>(GetField<uint8_t>(VT_FWDINFO2_TYPE, 0));
  }
  bool mutate_fwdinfo2_type(fwdinfo_u _fwdinfo2_type) {
    return SetField(VT_FWDINFO2_TYPE, static_cast<uint8_t>(_fwdinfo2_type));
  }
  const void *fwdinfo2() const {
    return GetPointer<const void *>(VT_FWDINFO2);
  }
  void *mutable_fwdinfo2() {
    return GetPointer<void *>(VT_FWDINFO2);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_NAME) &&
           verifier.Verify(name()) &&
           VerifyField<uint8_t>(verifier, VT_PV_TYPE) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_PV) &&
           VerifyPV(verifier, pv(), pv_type()) &&
           VerifyField<timeStamp_t>(verifier, VT_TIMESTAMP) &&
           VerifyField<fwdinfo_t>(verifier, VT_FWDINFO) &&
           VerifyField<uint8_t>(verifier, VT_FWDINFO2_TYPE) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_FWDINFO2) &&
           Verifyfwdinfo_u(verifier, fwdinfo2(), fwdinfo2_type()) &&
           verifier.EndTable();
  }
};

struct EpicsPVBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(EpicsPV::VT_NAME, name);
  }
  void add_pv_type(PV pv_type) {
    fbb_.AddElement<uint8_t>(EpicsPV::VT_PV_TYPE, static_cast<uint8_t>(pv_type), 0);
  }
  void add_pv(flatbuffers::Offset<void> pv) {
    fbb_.AddOffset(EpicsPV::VT_PV, pv);
  }
  void add_timeStamp(const timeStamp_t *timeStamp) {
    fbb_.AddStruct(EpicsPV::VT_TIMESTAMP, timeStamp);
  }
  void add_fwdinfo(const fwdinfo_t *fwdinfo) {
    fbb_.AddStruct(EpicsPV::VT_FWDINFO, fwdinfo);
  }
  void add_fwdinfo2_type(fwdinfo_u fwdinfo2_type) {
    fbb_.AddElement<uint8_t>(EpicsPV::VT_FWDINFO2_TYPE, static_cast<uint8_t>(fwdinfo2_type), 0);
  }
  void add_fwdinfo2(flatbuffers::Offset<void> fwdinfo2) {
    fbb_.AddOffset(EpicsPV::VT_FWDINFO2, fwdinfo2);
  }
  EpicsPVBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  EpicsPVBuilder &operator=(const EpicsPVBuilder &);
  flatbuffers::Offset<EpicsPV> Finish() {
    const auto end = fbb_.EndTable(start_, 7);
    auto o = flatbuffers::Offset<EpicsPV>(end);
    return o;
  }
};

inline flatbuffers::Offset<EpicsPV> CreateEpicsPV(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    PV pv_type = PV::NONE,
    flatbuffers::Offset<void> pv = 0,
    const timeStamp_t *timeStamp = 0,
    const fwdinfo_t *fwdinfo = 0,
    fwdinfo_u fwdinfo2_type = fwdinfo_u::NONE,
    flatbuffers::Offset<void> fwdinfo2 = 0) {
  EpicsPVBuilder builder_(_fbb);
  builder_.add_fwdinfo2(fwdinfo2);
  builder_.add_fwdinfo(fwdinfo);
  builder_.add_timeStamp(timeStamp);
  builder_.add_pv(pv);
  builder_.add_name(name);
  builder_.add_fwdinfo2_type(fwdinfo2_type);
  builder_.add_pv_type(pv_type);
  return builder_.Finish();
}

inline flatbuffers::Offset<EpicsPV> CreateEpicsPVDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    PV pv_type = PV::NONE,
    flatbuffers::Offset<void> pv = 0,
    const timeStamp_t *timeStamp = 0,
    const fwdinfo_t *fwdinfo = 0,
    fwdinfo_u fwdinfo2_type = fwdinfo_u::NONE,
    flatbuffers::Offset<void> fwdinfo2 = 0) {
  return BrightnESS::FlatBufs::f141_epics_nt::CreateEpicsPV(
      _fbb,
      name ? _fbb.CreateString(name) : 0,
      pv_type,
      pv,
      timeStamp,
      fwdinfo,
      fwdinfo2_type,
      fwdinfo2);
}

inline bool VerifyPV(flatbuffers::Verifier &verifier, const void *obj, PV type) {
  switch (type) {
    case PV::NONE: {
      return true;
    }
    case PV::NTScalarByte: {
      auto ptr = reinterpret_cast<const NTScalarByte *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PV::NTScalarUByte: {
      auto ptr = reinterpret_cast<const NTScalarUByte *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PV::NTScalarShort: {
      auto ptr = reinterpret_cast<const NTScalarShort *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PV::NTScalarUShort: {
      auto ptr = reinterpret_cast<const NTScalarUShort *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PV::NTScalarInt: {
      auto ptr = reinterpret_cast<const NTScalarInt *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PV::NTScalarUInt: {
      auto ptr = reinterpret_cast<const NTScalarUInt *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PV::NTScalarLong: {
      auto ptr = reinterpret_cast<const NTScalarLong *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PV::NTScalarULong: {
      auto ptr = reinterpret_cast<const NTScalarULong *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PV::NTScalarFloat: {
      auto ptr = reinterpret_cast<const NTScalarFloat *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PV::NTScalarDouble: {
      auto ptr = reinterpret_cast<const NTScalarDouble *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PV::NTScalarArrayByte: {
      auto ptr = reinterpret_cast<const NTScalarArrayByte *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PV::NTScalarArrayUByte: {
      auto ptr = reinterpret_cast<const NTScalarArrayUByte *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PV::NTScalarArrayShort: {
      auto ptr = reinterpret_cast<const NTScalarArrayShort *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PV::NTScalarArrayUShort: {
      auto ptr = reinterpret_cast<const NTScalarArrayUShort *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PV::NTScalarArrayInt: {
      auto ptr = reinterpret_cast<const NTScalarArrayInt *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PV::NTScalarArrayUInt: {
      auto ptr = reinterpret_cast<const NTScalarArrayUInt *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PV::NTScalarArrayLong: {
      auto ptr = reinterpret_cast<const NTScalarArrayLong *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PV::NTScalarArrayULong: {
      auto ptr = reinterpret_cast<const NTScalarArrayULong *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PV::NTScalarArrayFloat: {
      auto ptr = reinterpret_cast<const NTScalarArrayFloat *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PV::NTScalarArrayDouble: {
      auto ptr = reinterpret_cast<const NTScalarArrayDouble *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return false;
  }
}

inline bool VerifyPVVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types) {
  if (values->size() != types->size()) return false;
  for (flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyPV(
        verifier,  values->Get(i), types->GetEnum<PV>(i))) {
      return false;
    }
  }
  return true;
}

inline bool Verifyfwdinfo_u(flatbuffers::Verifier &verifier, const void *obj, fwdinfo_u type) {
  switch (type) {
    case fwdinfo_u::NONE: {
      return true;
    }
    case fwdinfo_u::fwdinfo_2_t: {
      auto ptr = reinterpret_cast<const fwdinfo_2_t *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return false;
  }
}

inline bool Verifyfwdinfo_uVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types) {
  if (values->size() != types->size()) return false;
  for (flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!Verifyfwdinfo_u(
        verifier,  values->Get(i), types->GetEnum<fwdinfo_u>(i))) {
      return false;
    }
  }
  return true;
}

inline const BrightnESS::FlatBufs::f141_epics_nt::EpicsPV *GetEpicsPV(const void *buf) {
  return flatbuffers::GetRoot<BrightnESS::FlatBufs::f141_epics_nt::EpicsPV>(buf);
}

inline EpicsPV *GetMutableEpicsPV(void *buf) {
  return flatbuffers::GetMutableRoot<EpicsPV>(buf);
}

inline const char *EpicsPVIdentifier() {
  return "f141";
}

inline bool EpicsPVBufferHasIdentifier(const void *buf) {
  return flatbuffers::BufferHasIdentifier(
      buf, EpicsPVIdentifier());
}

inline bool VerifyEpicsPVBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<BrightnESS::FlatBufs::f141_epics_nt::EpicsPV>(EpicsPVIdentifier());
}

inline void FinishEpicsPVBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<BrightnESS::FlatBufs::f141_epics_nt::EpicsPV> root) {
  fbb.Finish(root, EpicsPVIdentifier());
}

}  // namespace f141_epics_nt
}  // namespace FlatBufs
}  // namespace BrightnESS

#endif  // FLATBUFFERS_GENERATED_F141EPICSNT_BRIGHTNESS_FLATBUFS_F141_EPICS_NT_H_
