// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_F143STRUCTURE_F143_STRUCTURE_H_
#define FLATBUFFERS_GENERATED_F143STRUCTURE_F143_STRUCTURE_H_

#include "flatbuffers/flatbuffers.h"

#include "fwdi_forwarder_internal_generated.h"

namespace f143_structure {

struct Byte;

struct UByte;

struct Short;

struct UShort;

struct Int;

struct UInt;

struct Long;

struct ULong;

struct Float;

struct Double;

struct String;

struct ArrayByte;

struct ArrayUByte;

struct ArrayShort;

struct ArrayUShort;

struct ArrayInt;

struct ArrayUInt;

struct ArrayLong;

struct ArrayULong;

struct ArrayFloat;

struct ArrayDouble;

struct ArrayString;

struct ObjM;

struct Obj;

struct ArrayObj;

struct Structure;

enum class Value : uint8_t {
  NONE = 0,
  Byte = 1,
  Short = 2,
  Int = 3,
  Long = 4,
  UByte = 5,
  UShort = 6,
  UInt = 7,
  ULong = 8,
  Float = 9,
  Double = 10,
  String = 11,
  Obj = 12,
  ArrayByte = 13,
  ArrayShort = 14,
  ArrayInt = 15,
  ArrayLong = 16,
  ArrayUByte = 17,
  ArrayUShort = 18,
  ArrayUInt = 19,
  ArrayULong = 20,
  ArrayFloat = 21,
  ArrayDouble = 22,
  ArrayString = 23,
  ArrayObj = 24,
  MIN = NONE,
  MAX = ArrayObj
};

inline const char **EnumNamesValue() {
  static const char *names[] = {
    "NONE",
    "Byte",
    "Short",
    "Int",
    "Long",
    "UByte",
    "UShort",
    "UInt",
    "ULong",
    "Float",
    "Double",
    "String",
    "Obj",
    "ArrayByte",
    "ArrayShort",
    "ArrayInt",
    "ArrayLong",
    "ArrayUByte",
    "ArrayUShort",
    "ArrayUInt",
    "ArrayULong",
    "ArrayFloat",
    "ArrayDouble",
    "ArrayString",
    "ArrayObj",
    nullptr
  };
  return names;
}

inline const char *EnumNameValue(Value e) {
  const size_t index = static_cast<int>(e);
  return EnumNamesValue()[index];
}

template<typename T> struct ValueTraits {
  static const Value enum_value = Value::NONE;
};

template<> struct ValueTraits<Byte> {
  static const Value enum_value = Value::Byte;
};

template<> struct ValueTraits<Short> {
  static const Value enum_value = Value::Short;
};

template<> struct ValueTraits<Int> {
  static const Value enum_value = Value::Int;
};

template<> struct ValueTraits<Long> {
  static const Value enum_value = Value::Long;
};

template<> struct ValueTraits<UByte> {
  static const Value enum_value = Value::UByte;
};

template<> struct ValueTraits<UShort> {
  static const Value enum_value = Value::UShort;
};

template<> struct ValueTraits<UInt> {
  static const Value enum_value = Value::UInt;
};

template<> struct ValueTraits<ULong> {
  static const Value enum_value = Value::ULong;
};

template<> struct ValueTraits<Float> {
  static const Value enum_value = Value::Float;
};

template<> struct ValueTraits<Double> {
  static const Value enum_value = Value::Double;
};

template<> struct ValueTraits<String> {
  static const Value enum_value = Value::String;
};

template<> struct ValueTraits<Obj> {
  static const Value enum_value = Value::Obj;
};

template<> struct ValueTraits<ArrayByte> {
  static const Value enum_value = Value::ArrayByte;
};

template<> struct ValueTraits<ArrayShort> {
  static const Value enum_value = Value::ArrayShort;
};

template<> struct ValueTraits<ArrayInt> {
  static const Value enum_value = Value::ArrayInt;
};

template<> struct ValueTraits<ArrayLong> {
  static const Value enum_value = Value::ArrayLong;
};

template<> struct ValueTraits<ArrayUByte> {
  static const Value enum_value = Value::ArrayUByte;
};

template<> struct ValueTraits<ArrayUShort> {
  static const Value enum_value = Value::ArrayUShort;
};

template<> struct ValueTraits<ArrayUInt> {
  static const Value enum_value = Value::ArrayUInt;
};

template<> struct ValueTraits<ArrayULong> {
  static const Value enum_value = Value::ArrayULong;
};

template<> struct ValueTraits<ArrayFloat> {
  static const Value enum_value = Value::ArrayFloat;
};

template<> struct ValueTraits<ArrayDouble> {
  static const Value enum_value = Value::ArrayDouble;
};

template<> struct ValueTraits<ArrayString> {
  static const Value enum_value = Value::ArrayString;
};

template<> struct ValueTraits<ArrayObj> {
  static const Value enum_value = Value::ArrayObj;
};

bool VerifyValue(flatbuffers::Verifier &verifier, const void *obj, Value type);
bool VerifyValueVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types);

struct Byte FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "f143_structure.Byte";
  }
  enum {
    VT_VALUE = 4
  };
  int8_t value() const {
    return GetField<int8_t>(VT_VALUE, 0);
  }
  bool mutate_value(int8_t _value) {
    return SetField(VT_VALUE, _value);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_VALUE) &&
           verifier.EndTable();
  }
};

struct ByteBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(int8_t value) {
    fbb_.AddElement<int8_t>(Byte::VT_VALUE, value, 0);
  }
  ByteBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ByteBuilder &operator=(const ByteBuilder &);
  flatbuffers::Offset<Byte> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<Byte>(end);
    return o;
  }
};

inline flatbuffers::Offset<Byte> CreateByte(
    flatbuffers::FlatBufferBuilder &_fbb,
    int8_t value = 0) {
  ByteBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct UByte FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "f143_structure.UByte";
  }
  enum {
    VT_VALUE = 4
  };
  uint8_t value() const {
    return GetField<uint8_t>(VT_VALUE, 0);
  }
  bool mutate_value(uint8_t _value) {
    return SetField(VT_VALUE, _value);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_VALUE) &&
           verifier.EndTable();
  }
};

struct UByteBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(uint8_t value) {
    fbb_.AddElement<uint8_t>(UByte::VT_VALUE, value, 0);
  }
  UByteBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  UByteBuilder &operator=(const UByteBuilder &);
  flatbuffers::Offset<UByte> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<UByte>(end);
    return o;
  }
};

inline flatbuffers::Offset<UByte> CreateUByte(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t value = 0) {
  UByteBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct Short FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "f143_structure.Short";
  }
  enum {
    VT_VALUE = 4
  };
  int16_t value() const {
    return GetField<int16_t>(VT_VALUE, 0);
  }
  bool mutate_value(int16_t _value) {
    return SetField(VT_VALUE, _value);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int16_t>(verifier, VT_VALUE) &&
           verifier.EndTable();
  }
};

struct ShortBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(int16_t value) {
    fbb_.AddElement<int16_t>(Short::VT_VALUE, value, 0);
  }
  ShortBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ShortBuilder &operator=(const ShortBuilder &);
  flatbuffers::Offset<Short> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<Short>(end);
    return o;
  }
};

inline flatbuffers::Offset<Short> CreateShort(
    flatbuffers::FlatBufferBuilder &_fbb,
    int16_t value = 0) {
  ShortBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct UShort FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "f143_structure.UShort";
  }
  enum {
    VT_VALUE = 4
  };
  uint16_t value() const {
    return GetField<uint16_t>(VT_VALUE, 0);
  }
  bool mutate_value(uint16_t _value) {
    return SetField(VT_VALUE, _value);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_VALUE) &&
           verifier.EndTable();
  }
};

struct UShortBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(uint16_t value) {
    fbb_.AddElement<uint16_t>(UShort::VT_VALUE, value, 0);
  }
  UShortBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  UShortBuilder &operator=(const UShortBuilder &);
  flatbuffers::Offset<UShort> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<UShort>(end);
    return o;
  }
};

inline flatbuffers::Offset<UShort> CreateUShort(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t value = 0) {
  UShortBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct Int FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "f143_structure.Int";
  }
  enum {
    VT_VALUE = 4
  };
  int32_t value() const {
    return GetField<int32_t>(VT_VALUE, 0);
  }
  bool mutate_value(int32_t _value) {
    return SetField(VT_VALUE, _value);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_VALUE) &&
           verifier.EndTable();
  }
};

struct IntBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(int32_t value) {
    fbb_.AddElement<int32_t>(Int::VT_VALUE, value, 0);
  }
  IntBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  IntBuilder &operator=(const IntBuilder &);
  flatbuffers::Offset<Int> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<Int>(end);
    return o;
  }
};

inline flatbuffers::Offset<Int> CreateInt(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t value = 0) {
  IntBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct UInt FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "f143_structure.UInt";
  }
  enum {
    VT_VALUE = 4
  };
  uint32_t value() const {
    return GetField<uint32_t>(VT_VALUE, 0);
  }
  bool mutate_value(uint32_t _value) {
    return SetField(VT_VALUE, _value);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_VALUE) &&
           verifier.EndTable();
  }
};

struct UIntBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(uint32_t value) {
    fbb_.AddElement<uint32_t>(UInt::VT_VALUE, value, 0);
  }
  UIntBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  UIntBuilder &operator=(const UIntBuilder &);
  flatbuffers::Offset<UInt> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<UInt>(end);
    return o;
  }
};

inline flatbuffers::Offset<UInt> CreateUInt(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t value = 0) {
  UIntBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct Long FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "f143_structure.Long";
  }
  enum {
    VT_VALUE = 4
  };
  int64_t value() const {
    return GetField<int64_t>(VT_VALUE, 0);
  }
  bool mutate_value(int64_t _value) {
    return SetField(VT_VALUE, _value);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_VALUE) &&
           verifier.EndTable();
  }
};

struct LongBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(int64_t value) {
    fbb_.AddElement<int64_t>(Long::VT_VALUE, value, 0);
  }
  LongBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  LongBuilder &operator=(const LongBuilder &);
  flatbuffers::Offset<Long> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<Long>(end);
    return o;
  }
};

inline flatbuffers::Offset<Long> CreateLong(
    flatbuffers::FlatBufferBuilder &_fbb,
    int64_t value = 0) {
  LongBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct ULong FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "f143_structure.ULong";
  }
  enum {
    VT_VALUE = 4
  };
  uint64_t value() const {
    return GetField<uint64_t>(VT_VALUE, 0);
  }
  bool mutate_value(uint64_t _value) {
    return SetField(VT_VALUE, _value);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_VALUE) &&
           verifier.EndTable();
  }
};

struct ULongBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(uint64_t value) {
    fbb_.AddElement<uint64_t>(ULong::VT_VALUE, value, 0);
  }
  ULongBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ULongBuilder &operator=(const ULongBuilder &);
  flatbuffers::Offset<ULong> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<ULong>(end);
    return o;
  }
};

inline flatbuffers::Offset<ULong> CreateULong(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t value = 0) {
  ULongBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct Float FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "f143_structure.Float";
  }
  enum {
    VT_VALUE = 4
  };
  float value() const {
    return GetField<float>(VT_VALUE, 0.0f);
  }
  bool mutate_value(float _value) {
    return SetField(VT_VALUE, _value);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_VALUE) &&
           verifier.EndTable();
  }
};

struct FloatBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(float value) {
    fbb_.AddElement<float>(Float::VT_VALUE, value, 0.0f);
  }
  FloatBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  FloatBuilder &operator=(const FloatBuilder &);
  flatbuffers::Offset<Float> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<Float>(end);
    return o;
  }
};

inline flatbuffers::Offset<Float> CreateFloat(
    flatbuffers::FlatBufferBuilder &_fbb,
    float value = 0.0f) {
  FloatBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct Double FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "f143_structure.Double";
  }
  enum {
    VT_VALUE = 4
  };
  double value() const {
    return GetField<double>(VT_VALUE, 0.0);
  }
  bool mutate_value(double _value) {
    return SetField(VT_VALUE, _value);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_VALUE) &&
           verifier.EndTable();
  }
};

struct DoubleBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(double value) {
    fbb_.AddElement<double>(Double::VT_VALUE, value, 0.0);
  }
  DoubleBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  DoubleBuilder &operator=(const DoubleBuilder &);
  flatbuffers::Offset<Double> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<Double>(end);
    return o;
  }
};

inline flatbuffers::Offset<Double> CreateDouble(
    flatbuffers::FlatBufferBuilder &_fbb,
    double value = 0.0) {
  DoubleBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct String FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "f143_structure.String";
  }
  enum {
    VT_VALUE = 4
  };
  const flatbuffers::String *value() const {
    return GetPointer<const flatbuffers::String *>(VT_VALUE);
  }
  flatbuffers::String *mutable_value() {
    return GetPointer<flatbuffers::String *>(VT_VALUE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_VALUE) &&
           verifier.Verify(value()) &&
           verifier.EndTable();
  }
};

struct StringBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(flatbuffers::Offset<flatbuffers::String> value) {
    fbb_.AddOffset(String::VT_VALUE, value);
  }
  StringBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  StringBuilder &operator=(const StringBuilder &);
  flatbuffers::Offset<String> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<String>(end);
    return o;
  }
};

inline flatbuffers::Offset<String> CreateString(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> value = 0) {
  StringBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline flatbuffers::Offset<String> CreateStringDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *value = nullptr) {
  return f143_structure::CreateString(
      _fbb,
      value ? _fbb.CreateString(value) : 0);
}

struct ArrayByte FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "f143_structure.ArrayByte";
  }
  enum {
    VT_VALUE = 4
  };
  const flatbuffers::Vector<int8_t> *value() const {
    return GetPointer<const flatbuffers::Vector<int8_t> *>(VT_VALUE);
  }
  flatbuffers::Vector<int8_t> *mutable_value() {
    return GetPointer<flatbuffers::Vector<int8_t> *>(VT_VALUE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_VALUE) &&
           verifier.Verify(value()) &&
           verifier.EndTable();
  }
};

struct ArrayByteBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(flatbuffers::Offset<flatbuffers::Vector<int8_t>> value) {
    fbb_.AddOffset(ArrayByte::VT_VALUE, value);
  }
  ArrayByteBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ArrayByteBuilder &operator=(const ArrayByteBuilder &);
  flatbuffers::Offset<ArrayByte> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<ArrayByte>(end);
    return o;
  }
};

inline flatbuffers::Offset<ArrayByte> CreateArrayByte(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<int8_t>> value = 0) {
  ArrayByteBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline flatbuffers::Offset<ArrayByte> CreateArrayByteDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<int8_t> *value = nullptr) {
  return f143_structure::CreateArrayByte(
      _fbb,
      value ? _fbb.CreateVector<int8_t>(*value) : 0);
}

struct ArrayUByte FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "f143_structure.ArrayUByte";
  }
  enum {
    VT_VALUE = 4
  };
  const flatbuffers::Vector<uint8_t> *value() const {
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_VALUE);
  }
  flatbuffers::Vector<uint8_t> *mutable_value() {
    return GetPointer<flatbuffers::Vector<uint8_t> *>(VT_VALUE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_VALUE) &&
           verifier.Verify(value()) &&
           verifier.EndTable();
  }
};

struct ArrayUByteBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> value) {
    fbb_.AddOffset(ArrayUByte::VT_VALUE, value);
  }
  ArrayUByteBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ArrayUByteBuilder &operator=(const ArrayUByteBuilder &);
  flatbuffers::Offset<ArrayUByte> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<ArrayUByte>(end);
    return o;
  }
};

inline flatbuffers::Offset<ArrayUByte> CreateArrayUByte(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> value = 0) {
  ArrayUByteBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline flatbuffers::Offset<ArrayUByte> CreateArrayUByteDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *value = nullptr) {
  return f143_structure::CreateArrayUByte(
      _fbb,
      value ? _fbb.CreateVector<uint8_t>(*value) : 0);
}

struct ArrayShort FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "f143_structure.ArrayShort";
  }
  enum {
    VT_VALUE = 4
  };
  const flatbuffers::Vector<int16_t> *value() const {
    return GetPointer<const flatbuffers::Vector<int16_t> *>(VT_VALUE);
  }
  flatbuffers::Vector<int16_t> *mutable_value() {
    return GetPointer<flatbuffers::Vector<int16_t> *>(VT_VALUE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_VALUE) &&
           verifier.Verify(value()) &&
           verifier.EndTable();
  }
};

struct ArrayShortBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(flatbuffers::Offset<flatbuffers::Vector<int16_t>> value) {
    fbb_.AddOffset(ArrayShort::VT_VALUE, value);
  }
  ArrayShortBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ArrayShortBuilder &operator=(const ArrayShortBuilder &);
  flatbuffers::Offset<ArrayShort> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<ArrayShort>(end);
    return o;
  }
};

inline flatbuffers::Offset<ArrayShort> CreateArrayShort(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<int16_t>> value = 0) {
  ArrayShortBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline flatbuffers::Offset<ArrayShort> CreateArrayShortDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<int16_t> *value = nullptr) {
  return f143_structure::CreateArrayShort(
      _fbb,
      value ? _fbb.CreateVector<int16_t>(*value) : 0);
}

struct ArrayUShort FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "f143_structure.ArrayUShort";
  }
  enum {
    VT_VALUE = 4
  };
  const flatbuffers::Vector<uint16_t> *value() const {
    return GetPointer<const flatbuffers::Vector<uint16_t> *>(VT_VALUE);
  }
  flatbuffers::Vector<uint16_t> *mutable_value() {
    return GetPointer<flatbuffers::Vector<uint16_t> *>(VT_VALUE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_VALUE) &&
           verifier.Verify(value()) &&
           verifier.EndTable();
  }
};

struct ArrayUShortBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(flatbuffers::Offset<flatbuffers::Vector<uint16_t>> value) {
    fbb_.AddOffset(ArrayUShort::VT_VALUE, value);
  }
  ArrayUShortBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ArrayUShortBuilder &operator=(const ArrayUShortBuilder &);
  flatbuffers::Offset<ArrayUShort> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<ArrayUShort>(end);
    return o;
  }
};

inline flatbuffers::Offset<ArrayUShort> CreateArrayUShort(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<uint16_t>> value = 0) {
  ArrayUShortBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline flatbuffers::Offset<ArrayUShort> CreateArrayUShortDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint16_t> *value = nullptr) {
  return f143_structure::CreateArrayUShort(
      _fbb,
      value ? _fbb.CreateVector<uint16_t>(*value) : 0);
}

struct ArrayInt FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "f143_structure.ArrayInt";
  }
  enum {
    VT_VALUE = 4
  };
  const flatbuffers::Vector<int32_t> *value() const {
    return GetPointer<const flatbuffers::Vector<int32_t> *>(VT_VALUE);
  }
  flatbuffers::Vector<int32_t> *mutable_value() {
    return GetPointer<flatbuffers::Vector<int32_t> *>(VT_VALUE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_VALUE) &&
           verifier.Verify(value()) &&
           verifier.EndTable();
  }
};

struct ArrayIntBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(flatbuffers::Offset<flatbuffers::Vector<int32_t>> value) {
    fbb_.AddOffset(ArrayInt::VT_VALUE, value);
  }
  ArrayIntBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ArrayIntBuilder &operator=(const ArrayIntBuilder &);
  flatbuffers::Offset<ArrayInt> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<ArrayInt>(end);
    return o;
  }
};

inline flatbuffers::Offset<ArrayInt> CreateArrayInt(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<int32_t>> value = 0) {
  ArrayIntBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline flatbuffers::Offset<ArrayInt> CreateArrayIntDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<int32_t> *value = nullptr) {
  return f143_structure::CreateArrayInt(
      _fbb,
      value ? _fbb.CreateVector<int32_t>(*value) : 0);
}

struct ArrayUInt FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "f143_structure.ArrayUInt";
  }
  enum {
    VT_VALUE = 4
  };
  const flatbuffers::Vector<uint32_t> *value() const {
    return GetPointer<const flatbuffers::Vector<uint32_t> *>(VT_VALUE);
  }
  flatbuffers::Vector<uint32_t> *mutable_value() {
    return GetPointer<flatbuffers::Vector<uint32_t> *>(VT_VALUE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_VALUE) &&
           verifier.Verify(value()) &&
           verifier.EndTable();
  }
};

struct ArrayUIntBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(flatbuffers::Offset<flatbuffers::Vector<uint32_t>> value) {
    fbb_.AddOffset(ArrayUInt::VT_VALUE, value);
  }
  ArrayUIntBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ArrayUIntBuilder &operator=(const ArrayUIntBuilder &);
  flatbuffers::Offset<ArrayUInt> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<ArrayUInt>(end);
    return o;
  }
};

inline flatbuffers::Offset<ArrayUInt> CreateArrayUInt(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<uint32_t>> value = 0) {
  ArrayUIntBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline flatbuffers::Offset<ArrayUInt> CreateArrayUIntDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint32_t> *value = nullptr) {
  return f143_structure::CreateArrayUInt(
      _fbb,
      value ? _fbb.CreateVector<uint32_t>(*value) : 0);
}

struct ArrayLong FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "f143_structure.ArrayLong";
  }
  enum {
    VT_VALUE = 4
  };
  const flatbuffers::Vector<int64_t> *value() const {
    return GetPointer<const flatbuffers::Vector<int64_t> *>(VT_VALUE);
  }
  flatbuffers::Vector<int64_t> *mutable_value() {
    return GetPointer<flatbuffers::Vector<int64_t> *>(VT_VALUE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_VALUE) &&
           verifier.Verify(value()) &&
           verifier.EndTable();
  }
};

struct ArrayLongBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(flatbuffers::Offset<flatbuffers::Vector<int64_t>> value) {
    fbb_.AddOffset(ArrayLong::VT_VALUE, value);
  }
  ArrayLongBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ArrayLongBuilder &operator=(const ArrayLongBuilder &);
  flatbuffers::Offset<ArrayLong> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<ArrayLong>(end);
    return o;
  }
};

inline flatbuffers::Offset<ArrayLong> CreateArrayLong(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<int64_t>> value = 0) {
  ArrayLongBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline flatbuffers::Offset<ArrayLong> CreateArrayLongDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<int64_t> *value = nullptr) {
  return f143_structure::CreateArrayLong(
      _fbb,
      value ? _fbb.CreateVector<int64_t>(*value) : 0);
}

struct ArrayULong FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "f143_structure.ArrayULong";
  }
  enum {
    VT_VALUE = 4
  };
  const flatbuffers::Vector<uint64_t> *value() const {
    return GetPointer<const flatbuffers::Vector<uint64_t> *>(VT_VALUE);
  }
  flatbuffers::Vector<uint64_t> *mutable_value() {
    return GetPointer<flatbuffers::Vector<uint64_t> *>(VT_VALUE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_VALUE) &&
           verifier.Verify(value()) &&
           verifier.EndTable();
  }
};

struct ArrayULongBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(flatbuffers::Offset<flatbuffers::Vector<uint64_t>> value) {
    fbb_.AddOffset(ArrayULong::VT_VALUE, value);
  }
  ArrayULongBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ArrayULongBuilder &operator=(const ArrayULongBuilder &);
  flatbuffers::Offset<ArrayULong> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<ArrayULong>(end);
    return o;
  }
};

inline flatbuffers::Offset<ArrayULong> CreateArrayULong(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<uint64_t>> value = 0) {
  ArrayULongBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline flatbuffers::Offset<ArrayULong> CreateArrayULongDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint64_t> *value = nullptr) {
  return f143_structure::CreateArrayULong(
      _fbb,
      value ? _fbb.CreateVector<uint64_t>(*value) : 0);
}

struct ArrayFloat FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "f143_structure.ArrayFloat";
  }
  enum {
    VT_VALUE = 4
  };
  const flatbuffers::Vector<float> *value() const {
    return GetPointer<const flatbuffers::Vector<float> *>(VT_VALUE);
  }
  flatbuffers::Vector<float> *mutable_value() {
    return GetPointer<flatbuffers::Vector<float> *>(VT_VALUE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_VALUE) &&
           verifier.Verify(value()) &&
           verifier.EndTable();
  }
};

struct ArrayFloatBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(flatbuffers::Offset<flatbuffers::Vector<float>> value) {
    fbb_.AddOffset(ArrayFloat::VT_VALUE, value);
  }
  ArrayFloatBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ArrayFloatBuilder &operator=(const ArrayFloatBuilder &);
  flatbuffers::Offset<ArrayFloat> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<ArrayFloat>(end);
    return o;
  }
};

inline flatbuffers::Offset<ArrayFloat> CreateArrayFloat(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<float>> value = 0) {
  ArrayFloatBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline flatbuffers::Offset<ArrayFloat> CreateArrayFloatDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<float> *value = nullptr) {
  return f143_structure::CreateArrayFloat(
      _fbb,
      value ? _fbb.CreateVector<float>(*value) : 0);
}

struct ArrayDouble FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "f143_structure.ArrayDouble";
  }
  enum {
    VT_VALUE = 4
  };
  const flatbuffers::Vector<double> *value() const {
    return GetPointer<const flatbuffers::Vector<double> *>(VT_VALUE);
  }
  flatbuffers::Vector<double> *mutable_value() {
    return GetPointer<flatbuffers::Vector<double> *>(VT_VALUE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_VALUE) &&
           verifier.Verify(value()) &&
           verifier.EndTable();
  }
};

struct ArrayDoubleBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(flatbuffers::Offset<flatbuffers::Vector<double>> value) {
    fbb_.AddOffset(ArrayDouble::VT_VALUE, value);
  }
  ArrayDoubleBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ArrayDoubleBuilder &operator=(const ArrayDoubleBuilder &);
  flatbuffers::Offset<ArrayDouble> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<ArrayDouble>(end);
    return o;
  }
};

inline flatbuffers::Offset<ArrayDouble> CreateArrayDouble(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<double>> value = 0) {
  ArrayDoubleBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline flatbuffers::Offset<ArrayDouble> CreateArrayDoubleDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<double> *value = nullptr) {
  return f143_structure::CreateArrayDouble(
      _fbb,
      value ? _fbb.CreateVector<double>(*value) : 0);
}

struct ArrayString FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "f143_structure.ArrayString";
  }
  enum {
    VT_VALUE = 4
  };
  const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *value() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *>(VT_VALUE);
  }
  flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *mutable_value() {
    return GetPointer<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *>(VT_VALUE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_VALUE) &&
           verifier.Verify(value()) &&
           verifier.VerifyVectorOfStrings(value()) &&
           verifier.EndTable();
  }
};

struct ArrayStringBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> value) {
    fbb_.AddOffset(ArrayString::VT_VALUE, value);
  }
  ArrayStringBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ArrayStringBuilder &operator=(const ArrayStringBuilder &);
  flatbuffers::Offset<ArrayString> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<ArrayString>(end);
    return o;
  }
};

inline flatbuffers::Offset<ArrayString> CreateArrayString(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> value = 0) {
  ArrayStringBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline flatbuffers::Offset<ArrayString> CreateArrayStringDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<flatbuffers::Offset<flatbuffers::String>> *value = nullptr) {
  return f143_structure::CreateArrayString(
      _fbb,
      value ? _fbb.CreateVector<flatbuffers::Offset<flatbuffers::String>>(*value) : 0);
}

struct ObjM FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "f143_structure.ObjM";
  }
  enum {
    VT_K = 4,
    VT_V_TYPE = 6,
    VT_V = 8
  };
  const flatbuffers::String *k() const {
    return GetPointer<const flatbuffers::String *>(VT_K);
  }
  flatbuffers::String *mutable_k() {
    return GetPointer<flatbuffers::String *>(VT_K);
  }
  Value v_type() const {
    return static_cast<Value>(GetField<uint8_t>(VT_V_TYPE, 0));
  }
  bool mutate_v_type(Value _v_type) {
    return SetField(VT_V_TYPE, static_cast<uint8_t>(_v_type));
  }
  const void *v() const {
    return GetPointer<const void *>(VT_V);
  }
  void *mutable_v() {
    return GetPointer<void *>(VT_V);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_K) &&
           verifier.Verify(k()) &&
           VerifyField<uint8_t>(verifier, VT_V_TYPE) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_V) &&
           VerifyValue(verifier, v(), v_type()) &&
           verifier.EndTable();
  }
};

struct ObjMBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_k(flatbuffers::Offset<flatbuffers::String> k) {
    fbb_.AddOffset(ObjM::VT_K, k);
  }
  void add_v_type(Value v_type) {
    fbb_.AddElement<uint8_t>(ObjM::VT_V_TYPE, static_cast<uint8_t>(v_type), 0);
  }
  void add_v(flatbuffers::Offset<void> v) {
    fbb_.AddOffset(ObjM::VT_V, v);
  }
  ObjMBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ObjMBuilder &operator=(const ObjMBuilder &);
  flatbuffers::Offset<ObjM> Finish() {
    const auto end = fbb_.EndTable(start_, 3);
    auto o = flatbuffers::Offset<ObjM>(end);
    return o;
  }
};

inline flatbuffers::Offset<ObjM> CreateObjM(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> k = 0,
    Value v_type = Value::NONE,
    flatbuffers::Offset<void> v = 0) {
  ObjMBuilder builder_(_fbb);
  builder_.add_v(v);
  builder_.add_k(k);
  builder_.add_v_type(v_type);
  return builder_.Finish();
}

inline flatbuffers::Offset<ObjM> CreateObjMDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *k = nullptr,
    Value v_type = Value::NONE,
    flatbuffers::Offset<void> v = 0) {
  return f143_structure::CreateObjM(
      _fbb,
      k ? _fbb.CreateString(k) : 0,
      v_type,
      v);
}

struct Obj FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "f143_structure.Obj";
  }
  enum {
    VT_VALUE = 4
  };
  const flatbuffers::Vector<flatbuffers::Offset<ObjM>> *value() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<ObjM>> *>(VT_VALUE);
  }
  flatbuffers::Vector<flatbuffers::Offset<ObjM>> *mutable_value() {
    return GetPointer<flatbuffers::Vector<flatbuffers::Offset<ObjM>> *>(VT_VALUE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_VALUE) &&
           verifier.Verify(value()) &&
           verifier.VerifyVectorOfTables(value()) &&
           verifier.EndTable();
  }
};

struct ObjBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<ObjM>>> value) {
    fbb_.AddOffset(Obj::VT_VALUE, value);
  }
  ObjBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ObjBuilder &operator=(const ObjBuilder &);
  flatbuffers::Offset<Obj> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<Obj>(end);
    return o;
  }
};

inline flatbuffers::Offset<Obj> CreateObj(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<ObjM>>> value = 0) {
  ObjBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline flatbuffers::Offset<Obj> CreateObjDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<flatbuffers::Offset<ObjM>> *value = nullptr) {
  return f143_structure::CreateObj(
      _fbb,
      value ? _fbb.CreateVector<flatbuffers::Offset<ObjM>>(*value) : 0);
}

struct ArrayObj FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "f143_structure.ArrayObj";
  }
  enum {
    VT_VALUE = 4
  };
  const flatbuffers::Vector<flatbuffers::Offset<Obj>> *value() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<Obj>> *>(VT_VALUE);
  }
  flatbuffers::Vector<flatbuffers::Offset<Obj>> *mutable_value() {
    return GetPointer<flatbuffers::Vector<flatbuffers::Offset<Obj>> *>(VT_VALUE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_VALUE) &&
           verifier.Verify(value()) &&
           verifier.VerifyVectorOfTables(value()) &&
           verifier.EndTable();
  }
};

struct ArrayObjBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Obj>>> value) {
    fbb_.AddOffset(ArrayObj::VT_VALUE, value);
  }
  ArrayObjBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ArrayObjBuilder &operator=(const ArrayObjBuilder &);
  flatbuffers::Offset<ArrayObj> Finish() {
    const auto end = fbb_.EndTable(start_, 1);
    auto o = flatbuffers::Offset<ArrayObj>(end);
    return o;
  }
};

inline flatbuffers::Offset<ArrayObj> CreateArrayObj(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Obj>>> value = 0) {
  ArrayObjBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline flatbuffers::Offset<ArrayObj> CreateArrayObjDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<flatbuffers::Offset<Obj>> *value = nullptr) {
  return f143_structure::CreateArrayObj(
      _fbb,
      value ? _fbb.CreateVector<flatbuffers::Offset<Obj>>(*value) : 0);
}

struct Structure FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "f143_structure.Structure";
  }
  enum {
    VT_NAME = 4,
    VT_VALUE_TYPE = 6,
    VT_VALUE = 8,
    VT_TIMESTAMP = 10,
    VT_FWDINFO_TYPE = 12,
    VT_FWDINFO = 14
  };
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  flatbuffers::String *mutable_name() {
    return GetPointer<flatbuffers::String *>(VT_NAME);
  }
  Value value_type() const {
    return static_cast<Value>(GetField<uint8_t>(VT_VALUE_TYPE, 0));
  }
  bool mutate_value_type(Value _value_type) {
    return SetField(VT_VALUE_TYPE, static_cast<uint8_t>(_value_type));
  }
  const void *value() const {
    return GetPointer<const void *>(VT_VALUE);
  }
  void *mutable_value() {
    return GetPointer<void *>(VT_VALUE);
  }
  uint64_t timestamp() const {
    return GetField<uint64_t>(VT_TIMESTAMP, 0);
  }
  bool mutate_timestamp(uint64_t _timestamp) {
    return SetField(VT_TIMESTAMP, _timestamp);
  }
  forwarder_internal fwdinfo_type() const {
    return static_cast<forwarder_internal>(GetField<uint8_t>(VT_FWDINFO_TYPE, 0));
  }
  bool mutate_fwdinfo_type(forwarder_internal _fwdinfo_type) {
    return SetField(VT_FWDINFO_TYPE, static_cast<uint8_t>(_fwdinfo_type));
  }
  const void *fwdinfo() const {
    return GetPointer<const void *>(VT_FWDINFO);
  }
  void *mutable_fwdinfo() {
    return GetPointer<void *>(VT_FWDINFO);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_NAME) &&
           verifier.Verify(name()) &&
           VerifyField<uint8_t>(verifier, VT_VALUE_TYPE) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_VALUE) &&
           VerifyValue(verifier, value(), value_type()) &&
           VerifyField<uint64_t>(verifier, VT_TIMESTAMP) &&
           VerifyField<uint8_t>(verifier, VT_FWDINFO_TYPE) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_FWDINFO) &&
           Verifyforwarder_internal(verifier, fwdinfo(), fwdinfo_type()) &&
           verifier.EndTable();
  }
};

struct StructureBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(Structure::VT_NAME, name);
  }
  void add_value_type(Value value_type) {
    fbb_.AddElement<uint8_t>(Structure::VT_VALUE_TYPE, static_cast<uint8_t>(value_type), 0);
  }
  void add_value(flatbuffers::Offset<void> value) {
    fbb_.AddOffset(Structure::VT_VALUE, value);
  }
  void add_timestamp(uint64_t timestamp) {
    fbb_.AddElement<uint64_t>(Structure::VT_TIMESTAMP, timestamp, 0);
  }
  void add_fwdinfo_type(forwarder_internal fwdinfo_type) {
    fbb_.AddElement<uint8_t>(Structure::VT_FWDINFO_TYPE, static_cast<uint8_t>(fwdinfo_type), 0);
  }
  void add_fwdinfo(flatbuffers::Offset<void> fwdinfo) {
    fbb_.AddOffset(Structure::VT_FWDINFO, fwdinfo);
  }
  StructureBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  StructureBuilder &operator=(const StructureBuilder &);
  flatbuffers::Offset<Structure> Finish() {
    const auto end = fbb_.EndTable(start_, 6);
    auto o = flatbuffers::Offset<Structure>(end);
    return o;
  }
};

inline flatbuffers::Offset<Structure> CreateStructure(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    Value value_type = Value::NONE,
    flatbuffers::Offset<void> value = 0,
    uint64_t timestamp = 0,
    forwarder_internal fwdinfo_type = forwarder_internal::NONE,
    flatbuffers::Offset<void> fwdinfo = 0) {
  StructureBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_fwdinfo(fwdinfo);
  builder_.add_value(value);
  builder_.add_name(name);
  builder_.add_fwdinfo_type(fwdinfo_type);
  builder_.add_value_type(value_type);
  return builder_.Finish();
}

inline flatbuffers::Offset<Structure> CreateStructureDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    Value value_type = Value::NONE,
    flatbuffers::Offset<void> value = 0,
    uint64_t timestamp = 0,
    forwarder_internal fwdinfo_type = forwarder_internal::NONE,
    flatbuffers::Offset<void> fwdinfo = 0) {
  return f143_structure::CreateStructure(
      _fbb,
      name ? _fbb.CreateString(name) : 0,
      value_type,
      value,
      timestamp,
      fwdinfo_type,
      fwdinfo);
}

inline bool VerifyValue(flatbuffers::Verifier &verifier, const void *obj, Value type) {
  switch (type) {
    case Value::NONE: {
      return true;
    }
    case Value::Byte: {
      auto ptr = reinterpret_cast<const Byte *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Value::Short: {
      auto ptr = reinterpret_cast<const Short *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Value::Int: {
      auto ptr = reinterpret_cast<const Int *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Value::Long: {
      auto ptr = reinterpret_cast<const Long *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Value::UByte: {
      auto ptr = reinterpret_cast<const UByte *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Value::UShort: {
      auto ptr = reinterpret_cast<const UShort *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Value::UInt: {
      auto ptr = reinterpret_cast<const UInt *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Value::ULong: {
      auto ptr = reinterpret_cast<const ULong *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Value::Float: {
      auto ptr = reinterpret_cast<const Float *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Value::Double: {
      auto ptr = reinterpret_cast<const Double *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Value::String: {
      auto ptr = reinterpret_cast<const String *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Value::Obj: {
      auto ptr = reinterpret_cast<const Obj *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Value::ArrayByte: {
      auto ptr = reinterpret_cast<const ArrayByte *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Value::ArrayShort: {
      auto ptr = reinterpret_cast<const ArrayShort *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Value::ArrayInt: {
      auto ptr = reinterpret_cast<const ArrayInt *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Value::ArrayLong: {
      auto ptr = reinterpret_cast<const ArrayLong *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Value::ArrayUByte: {
      auto ptr = reinterpret_cast<const ArrayUByte *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Value::ArrayUShort: {
      auto ptr = reinterpret_cast<const ArrayUShort *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Value::ArrayUInt: {
      auto ptr = reinterpret_cast<const ArrayUInt *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Value::ArrayULong: {
      auto ptr = reinterpret_cast<const ArrayULong *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Value::ArrayFloat: {
      auto ptr = reinterpret_cast<const ArrayFloat *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Value::ArrayDouble: {
      auto ptr = reinterpret_cast<const ArrayDouble *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Value::ArrayString: {
      auto ptr = reinterpret_cast<const ArrayString *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Value::ArrayObj: {
      auto ptr = reinterpret_cast<const ArrayObj *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return false;
  }
}

inline bool VerifyValueVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types) {
  if (values->size() != types->size()) return false;
  for (flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyValue(
        verifier,  values->Get(i), types->GetEnum<Value>(i))) {
      return false;
    }
  }
  return true;
}

inline const f143_structure::Structure *GetStructure(const void *buf) {
  return flatbuffers::GetRoot<f143_structure::Structure>(buf);
}

inline Structure *GetMutableStructure(void *buf) {
  return flatbuffers::GetMutableRoot<Structure>(buf);
}

inline const char *StructureIdentifier() {
  return "f143";
}

inline bool StructureBufferHasIdentifier(const void *buf) {
  return flatbuffers::BufferHasIdentifier(
      buf, StructureIdentifier());
}

inline bool VerifyStructureBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<f143_structure::Structure>(StructureIdentifier());
}

inline void FinishStructureBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<f143_structure::Structure> root) {
  fbb.Finish(root, StructureIdentifier());
}

}  // namespace f143_structure

#endif  // FLATBUFFERS_GENERATED_F143STRUCTURE_F143_STRUCTURE_H_
