
version: '2'

services:
  kafka:
    image: wurstmeister/kafka:1.0.0
    depends_on:
      - zookeeper
    hostname: kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 10000000
      KAFKA_BROKER_ID: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  zookeeper:
    image: zookeeper:3.4
    restart: unless-stopped

  forwarder:
    build: ../
    depends_on:
      - kafka
    network_mode: "host"
    volumes:
      - ./forwarder_config_fake_epics.json:/forwarder_config_fake_epics.json
    environment:
      CONFIG_FILE: "/forwarder_config_fake_epics.json"
      FAKE_PV_PERIOD_MS: "1000"
