set(REQUIRE_GTEST FALSE CACHE BOOL "Require Google Test")
if (REQUIRE_GTEST)
	find_library(GMOCK_MAIN_LIB gmock_main)
	if (GMOCK_MAIN_LIB)
		message(STATUS "Google Test found")
		set(have_gtest TRUE)
	else()
		message(FATAL_ERROR "Google Test required but not found")
	endif()
else()
	message(STATUS "Tests disabled")
endif()

function(add_gtest_to_target tgt)
	if (have_gtest)
		target_compile_definitions(${tgt} PRIVATE HAVE_GTEST=1)
		target_link_libraries(${tgt} ${GMOCK_MAIN_LIB})
	endif()
endfunction()
