find_path(path_include_rdkafka NAMES librdkafka/rdkafka.h)
find_library(path_library_rdkafka NAMES rdkafka)
add_library(librdkafka SHARED IMPORTED)
set_property(TARGET librdkafka PROPERTY IMPORTED_LOCATION ${path_library_rdkafka})
message(STATUS "path_include_rdkafka ${path_include_rdkafka}")
message(STATUS "path_library_rdkafka ${path_library_rdkafka}")
