# opt-in (as requested)
set(USE_GRAYLOG_LOGGER FALSE CACHE BOOL "Try to use graylog_logger")
if (USE_GRAYLOG_LOGGER)
	find_path(path_include_graylog_logger NAMES graylog_logger/Log.hpp)
	find_library(path_library_graylog_logger NAMES graylog_logger)
	if (path_include_graylog_logger AND path_library_graylog_logger)
		message(STATUS "Using graylog_logger")
		message(STATUS "path_include_graylog_logger ${path_include_graylog_logger}")
		message(STATUS "path_library_graylog_logger ${path_library_graylog_logger}")
		set(have_graylog_logger TRUE)
	endif()

	if (NOT have_graylog_logger)
		message(WARNING "graylog_logger requested but not found")
	else()
		add_library(libgraylog_logger SHARED IMPORTED)
		set_property(TARGET libgraylog_logger PROPERTY IMPORTED_LOCATION ${path_library_graylog_logger})
	endif()

endif()
