set(PCREX_FOUND FALSE)
set(PCRE2_CODE_UNIT_WIDTH 8)

if(DEFINED PCREX_INCLUDE_DIRS)
    if (EXISTS ${PCREX_INCLUDE_DIRS}/pcre.h)
        message(STATUS "Using PCRE1")
        set(PCREX_MAJOR 1)
    elseif (EXISTS ${PCREX_INCLUDE_DIRS}/pcre2.h)
        message(STATUS "Using PCRE2")
        set(PCREX_MAJOR 2)
    endif()
else()
    find_path(PCREX_INCLUDE_DIRS NAMES pcre2.h)
    if (PCREX_INCLUDE_DIRS)
        message(STATUS "Using PCRE2")
        set(PCREX_MAJOR 2)
    endif()
endif()

find_library(PCREX_LIBRARIES NAMES "pcre2-${PCRE2_CODE_UNIT_WIDTH}")

if (PCREX_INCLUDE_DIRS AND PCREX_LIBRARIES)
    set(PCREX_FOUND TRUE)
else()
    find_path(PCREX_INCLUDE_DIRS NAMES pcre2.h)
    find_library(PCREX_LIBRARIES NAMES pcre)
    if (PCREX_INCLUDE_DIRS AND PCREX_LIBRARIES)
        message(STATUS "Using PCRE1")
        set(PCREX_MAJOR 1)
        set(PCREX_FOUND TRUE)
    endif()
endif()

if (NOT (PCREX_INCLUDE_DIRS AND PCREX_LIBRARIES))
    if (PCREX_FIND_REQUIRED OR NOT PCREX_FIND_QUIETLY)
        message(WARNING "Could not find PCRE or PCRE2")
    endif()
    if (PCREX_FIND_REQUIRED)
        message(FATAL_ERROR "Abort because PCREX is REQUIRED")
    endif()
endif()
